### ISSUE TITLE
Draw hierarchy of node in defaultDrawNodeHover function

### ISSUE THREAD

**Issue by StockerGaming** [jacomyal/sigma.js#1444]
When writing custom node hover renderers, the node is always drawn on top of any elements drawn by this function. An option to set the draw hierarchy of the node in regards to the rendered hover elements would be much appreciated. 

Many thanks.

**Comment by jacomyal** [comment]
The best way to do this is to customize the `z-index` CSS values for the canvas layers. Something like:

```css
.sigma-hovers {
  z-index: 2;
}
.sigma-hoverNodes {
  z-index: 1;
}
.sigma-mouse {
  /* keep this layer on top to preserve interactions: */
  z-index: 3;
}
```

This should do the trick.
